### ISSUE TITLE
PNG cartridges

### ISSUE THREAD

**Issue by Shatur** [eduardofilo/RG350_adam_image#322]
### What happened?

Pico-8 and TIC-80 supports cartridges as PNG images (TIC-80 supports it starting from [0.90.1723](https://github.com/nesbox/TIC-80/releases/tag/v0.90.1723), scroll down a little bit).
But such cartridges opens as images using the RetroArch image viewer. To fix this we should disable image viewer by toggling `Retroarch Settings > File Browser > Use Built-In Image Viewer`.

For TIC-80 we also need to add `.png` here:
https://github.com/eduardofilo/RG350_adam_image/blob/9472a7bb49b32344382865f418a007d12ee7a178/data/local/home/.simplemenu/section_groups/home%20computers.ini#L69
But for TIC-80 it won't start with this extension.

Here is a command to save game as PNG:

```bash
tic80 --cli --fs . --cmd "load game.tic & save game.png & exit"
```
After this command I can successfully run the generated PNG on my PC, but it fails to start on my handheld with "code is empty" error. I can reproduce the issue on my computer when I trying to load a PNG cartridge with a .tic extension (instead of .png). So I assume that the issue is related to the extension detection, but not sure how we can solve it.

### Device

RG280V

### Version

v2.1

**Comment by Shatur** [comment]
There is a similar issue with PICO-8 - carts won't open in RetroArch, but works on other. I mentioned this problem [here](https://github.com/eduardofilo/RG350_adam_image/discussions/265#discussioncomment-4334379), I believe it's related.

**Comment by eduardofilo** [comment]
Perhaps the problem is that the version of TIC-80 wrapped in the RetroArch core is based on a version prior to 0.90.1723. According to the core_info of the latest stable version of RetroArch for ODbeta, it is based on 0.80.0.

I am closing the issue as I have merged the PR you did to solve the PNG upload. Thanks again.

**Comment by Shatur** [comment]
@eduardofilo thanks for looking into it!
Looks like TIC-80 have [an option to build a core](https://github.com/nesbox/TIC-80/blob/148537bd62ad86963e63c93356431b5c4e7e2f81/CMakeLists.txt#LL78C14-L78C19) for RetroArch. Can we compile the latest version for Adam image?

**Comment by eduardofilo** [comment]
Go on. Please try. I think you have more skill than me with cmake projects.

**Comment by Shatur** [comment]
@eduardofilo I successfully compiled the latest version (v1.0.2164) from scratch (you need to cherry-pick https://github.com/nesbox/TIC-80/commit/d10fa217c05dc6733dda9dd8fcfd48477fba9a1e, won't be necessary in the next release) and put the resulted `tic80_libretro.so` to `local/home/.retroarch/cores/` and replaced the old one. Unfortunately, this did not fix the problem. I'm going to open an issue in the TIC-80 repo.
But how can I upstream a never version to the Adam image? It would be nice to update the core anyway. Here is the binary: [tic80_libretro.zip](https://github.com/eduardofilo/RG350_adam_image/files/10210205/tic80_libretro.zip).

**Comment by Shatur** [comment]
Opened: https://github.com/nesbox/TIC-80/issues/2048

**Comment by eduardofilo** [comment]
The integration of RetroArch in Adam is done through this repository that is integrated as a submodule.
https://github.com/eduardofilo/RG350_auto_ra_installer

This repository takes the cores from the official distribution. But when in the past I had problems with the DOSBox core, I reserved in the assets directory a copy of the working core which is then manually copied just before packaging the image, as you can see here:
https://github.com/eduardofilo/RG350_adam_image/blob/master/build.sh#L169

So when you get the core with the problem solved, we can incorporate it this way if the modification takes time to enter upstream in the official RetroArch distribution.
