### ISSUE TITLE
Instability of V1.3 on RG350

### ISSUE THREAD

**Issue by fantinomaurizio** [eduardofilo/RG350_adam_image#58]
I always used the Rogue RG250 firmware and very much appreciate its smoothness, but I run into the Adam image recently and liked the spirit. So I flashed on my RG350. The problem is that I did it already 11 times...

After a while, without any apparent reason after a shutdown it stops working and I run into a dead loop. The screen keep looping in the OpenDingux Loading... then black screen, then back again OpenDingux Loading... and black screen forever. I got out from the loop just pressing the power button with the result to see the unmount screen and shutdown operation properly done. For solving the problem so far the only solution is to reflash the image till suddenly the issue comes back again.

Since the flashing operation on the RG350 is quite annoying since you need to unscrew the console, I would kindly ask if you may understand which is the issue here.

Both the internal and game SD card are Samsung high quality EVO SD card, so I exclude that the sd card is the issue.

Thanks,

Maurizio

**Comment by iammeat** [comment]
When you flashed the image, did you go into the command line and select the correct kernel as described in the README file and the video guide by Retro Game Corps?

**Comment by fantinomaurizio** [comment]
> When you flashed the image, did you go into the command line and select the correct kernel as described in the README file and the video guide by Retro Game Corps?

Yes sure, otherwise it won't boot. The issue does not come at the first boot. I can play with the image for a couple of days, but suddenly after a shutdown and a reboot (maybe 30 minutes later or 2 days later) the image freeze in this deadloop of Loading for 2 sec, than black screen for 1 second and back again in Loading for 2 sec.

The issue is always the same, same freezing loop that it is solved with a reflash of the internal SD card and that it will represent itself sometimes later.

Even removing the external SD card with all the roms installed the issue still remain.

**Comment by borderomm** [comment]
I have the exact same issue in my RG350.
I started using Adam image for the 1st time 3 days ago (v.1.3) and already faced this same problem 2 or 3 times.
Last time just a few hours ago.

It is also driving me crazy as I cannot understand what I am doing wrong to cause it. I barely touch the internal card, I have only been adding roms and testing systems, so all the work is in the external card.

I was very happy to find that the issue is not mine but seems a general bug.

I confirm how annoying it is to unscrew the device every single time.

Thanks for taking a look into this

**Comment by ricar2009** [comment]
Hello guys! I can confirm that this is an issue with the Adam Image and not the SD card.

1. This issue happens apparently in a random manner (But the odds of occurring increase when modifying contents in the external (EXT) SD card. I.e.: Adding, removing, or replacing ROM files, scrapper images, and/or renaming files and directories)
2. This issue can still occur if playing Play Station games you make use of whatever saving feature a particular game has to store the gameplay into a Play Station Memory Card. The odds of this issue occurring increase with the number of saved gameplays you have across your Play Station games library and/or substituting particular gameplay multiple times by using the same memory slot in the game.
3. This issue seems to happen more often when the file "consoles.ini" is modified by the user in order to remove the ".bin" extension from the Play Station line that includes the types of files that are admissible to populate the game list for this system. The file is located at "/media/data/local/home/.simplemenu/section_groups/consoles.ini"
3.1 This scenario may or may not be related to the modification of the file itself but can also be related to the use of the built-in Commander app in the Adam Image to make these changes. More experimentation is needed to establish if it is possible that this app is corrupting the file after its modification or this file is being checked by the system at start-up and having a different value in size is causing it to crash.

This loop of death that is being experienced by the users happens in disregard of the SD card manufacturer, size, and OS used to partition it and format it. It also happens in disregard of CHKDSK finding 0 errors in the drive. 

Right before the system crashes and restarts itself, it's clear that is unable to find a specific file. With the combination of POWER + Y key, users are able to see at startup de command line describing this situation however, the file or directory in question is unknown. If the developers are able to pinpoint this file or directory it would be much easier to understand what is the root issue of this problem.
As I mentioned before if the file is corrupted or there is a discrepancy in its attributes such as size, extension, etc. and the system is unable to verify it more likely than not this will be enough to crash the entire system prompting a restart and perpetuating the situation as a boot loop.

For the time being, once you have restored your system to a working Adam Image 1.3, please, do not modify the "consoles.ini" file and do not use the in-game saving feature for Play Station titles, instead use the emulator's saving feature.

These attestations are made based on my own research and experience. I just want to contribute to this great community.

**Comment by Phluffhead55** [comment]
I've had the same issue on my rg350 and on my rg280v with 1.3.  Been using version 1.2 with no issues

**Comment by ricar2009** [comment]
Yes, that is correct. I was not able to recreate this problem with Adam Image 1.2. This happens only with Adam Image 1.3, particularly when the criteria I described in my previous post are met.

**Comment by fantinomaurizio** [comment]
Thanks @ricar2009 indeed you made me notice that this has always happened after or just after the upload of a full rompack session for an emulator. At the first reboot it happened to experience the loop of death.

**Comment by borderomm** [comment]
I can also confirm that I modified consoles.ini file with the commander, at least twice during my several image flashing.
So, one more possibility of having to do with.
I haven't done it since the last reimage, nor used PS emulation.
Let's see if it doesn't happen anymore

**Comment by eduardofilo** [comment]
In view of @fantinomaurizio's video, it seems clear to me that the problem is that SimpleMenu has problems and closes. As it is the default frontend, it is reloaded and closed again. To all of you who experience this problem, you can do one of these things (or both if the first one fails):

1. Try to delete the file at path: `/media/data/local/home/.simplemenu/last_state.sav`. As the frontend does not finish booting, the only way of doing is by SSH/SCP/SFTP.
2. After flashing, disable SimpleMenu as default launcher. This can be done in two ways:
    * By mean of settings menu if SimpleMenu works.
    * Deleting the file `/media/data/local/home/.autostart` by SSH/SCP/SFTP.

By disabling SimpleMenu as default launcher, you will see GMenu2X as launcher. From them, you can open SimpleMenu manually. If the problems begins, at least you will have control over the console and you will can open Commander to delete the `last_state.sav` file for instance.

**Comment by borderomm** [comment]
well, this just happened to me again, when i was about to follow your recommendation of disabling Simple Menu.
Unfortunately ssh doesn't work, don't know why (I use debian and i don't see 10.1.1.2 when i connect the rg350 onto my computer).
So i have to open it up again :(

I hope you can identify a fix for this

**Comment by borderomm** [comment]
nevermind, it was a faulty cable. I am in and deleted the file and my Rg350 is back up.

**Comment by borderomm** [comment]
Closed?
Is there a solution without the need to delete the sav file each time it happens?
I needed to do this at least 3 times today.

**Comment by eduardofilo** [comment]
I don't develop SimpleMenu, I just installed and configured it in the image. And I do not experience these problems either so I have not been able to investigate the reasons or if something can be improved so that it does not happen. I'm sorry.

Of course, modifying the ini files is reasonable to cause the application to close. Every time I have to add a new system, I make copies of the files and take the steps very carefully. The last_state.sav file is normal to have to be deleted in these cases since it may not correspond well with the new systems configuration in the modified ini's.

And of course, in case of modifying the ini, or adding new ROMs in the corresponding directories, especially if they are from systems that require multiple files per game (such as DOSBox or ScummVM), always disable SimpleMenu as the default launcher, to not loose control over the frontend.

**Comment by eduardofilo** [comment]
> Yes, that is correct. I was not able to recreate this problem with Adam Image 1.2. This happens only with Adam Image 1.3, particularly when the criteria I described in my previous post are met.

In 1.3 I installed a new version of SimpleMenu. It was also a prerelease. You can try to downgrade to the version of SimpleMenu installed in 1.2 to see if improves stability. That version was:
https://github.com/fgl82/simplemenu/releases/tag/10.2

**Comment by borderomm** [comment]
> I don't develop SimpleMenu, I just installed and configured it in the image. And I do not experience these problems either so I have not been able to investigate the reasons or if something can be improved so that it does not happen. I'm sorry.
> 
> Of course, modifying the ini files is reasonable to cause the application to close. Every time I have to add a new system, I make copies of the files and take the steps very carefully. The last_state.sav file is normal to have to be deleted in these cases since it may not correspond well with the new systems configuration in the modified ini's.
> 
> And of course, in case of modifying the ini, or adding new ROMs in the corresponding directories, especially if they are from systems that require multiple files per game (such as DOSBox or ScummVM), always disable SimpleMenu as the default launcher, to not loose control over the frontend.

Thanks for taking your time to review this.
My issue is that this bug impacts my user journey with the device.
I love and need to have simple menu as default. The biggest reason are my kids. It allows me to lend them the device with an SD card with only a couple of games allowed for them and let them use it.
With this bug, i cannot as GMenu2x is too complicated and risky that they can mess up something.

I'll try the downgraded version and see how it goes

**Comment by eduardofilo** [comment]
@borderomm Well, I was referring to setting GMenu2X as the default launcher when making modifications to files (INI's or ROMs). But in stable conditions, SimpleMenu shouldn't be a problem. If the version I installed in the 1.3 image is too unstable as it appears, perhaps the developer of this application could be informed. Although as I say the version I installed was a release candidate. Perhaps it would be better to wait for an official version to be released to comment on these problems. Meanwhile, try to install the latest official version ([10.3](https://github.com/fgl82/simplemenu/releases/tag/10.3)) or the one in the image 1.2 ([10.2](https://github.com/fgl82/simplemenu/releases/tag/10.2)).

**Comment by ricar2009** [comment]
I agree with @eduardofilo This issue should be closed since he is not responsible for Simple Menu's code and he was able to trace the problem back to this launcher.

The three walkarounds for people experiencing this problem have been addressed by Eduardo:
1. Roll back to the previous Adam Image (version 1.2) by performing a clean installation.
2. If you would like to keep Adam Image 1.3, disable Simple Menu as the default launcher following Eduardo steps and avoid the actions I described in my first post (Particularly DO NOT modify the .ini file that contains the consoles' admissable file extensions for each system)
3. If you would like to keep Adam Image 1.3, but you STILL want to be able to modify the .ini file or any additional parameters at your own risk, you can uninstall the Simple Menu shipped with Adam Image 1.3 and replace it with the more stable version that was released with Adam Image 1.2 (Follow Eduardo link to download Simple Menu stable version)

I would like to say thanks to Eduardo for his work supporting this community, I am sure that when a more stable version of Simple Menu is available this issue would go away.

Have a good weekend guys!

**Comment by borderomm** [comment]
Thanks again for taking your time on commenting on this.
Just to be clear, I understand where the issue could be (i still didn't have the time to downgrade and confirm it 100%), in Simple Menu.
And I am grateful for the options given here.
On the other hand, if the issue is in Simple Menu but those issues were brought here, within Adam's build, there is in theory something that could be done.
If a bad build caused a regression/issue in the software, there should be a rollback, in the way of maybe uploading a new Adam's build with a healthy version of Simple Menu.
The reason I am saying this is because not everybody may realize there is a closed topic around this (this one) and find the "temporary fix" until a new Adam image is built... and built Adam's image for the problem.

It could be also that I may be one of the few folks still using an RG350 and maybe nobody else will notice ;)

Anyhow, I'll check other Simple Menu's versions right away.

Thanks again and also thank you for this wonderful image.

**Comment by borderomm** [comment]
> 2. If you would like to keep Adam Image 1.3, disable Simple Menu as the default launcher following Eduardo steps and avoid the actions I described in my first post (Particularly DO NOT modify the .ini file that contains the consoles' admissable file extensions for each system)

I got into the boot loop without modifying any .ini file, just by using the console.
Then i don't think these steps are needed to cause the issue

**Comment by ricar2009** [comment]
@borderomm  I understand your situation. However, this still apply to those people that have never had this problem until they modified that file.

In your situation, I would stay away from using any saving feature when playing games. (If a game at any point asks you to save/store data don’t allow it) Use the emulator’s saving feature instead (You have plenty of slots to save your progress) It is possible that some games will only run if you save data first, in those scenarios I’m afraid that you are better off not playing them.

If you still encounter problems after this, you can just go ahead and go back to a stable version of Simple Menu. It’s well worth the time since you will be able to play your games with peace of mind.

My best guess about why this is happening is probably because Simple Menu is corrupting one or more files in the SD card and that’s probably why every time a game saves data, or a user modifies content the system is not able to start in the next session, hence causing a boot loop of it is set as the default launcher.

Let us know how your handheld behaves after using the stable version for Simple Menu. 

💪🏻😀

**Comment by borderomm** [comment]
It seems that with the 10.3 the device is working as expected.
I am not very proficient with Simple Menu and all its versions yet, i used to have other OS before. In order for it to make it work, i needed the SimpleMenu-OD-BETA.opk and not the -OD.opk
Not sure what the differences are but the -OD.opk doesn't boot.
The -OD-BETA one shares the name with the one that was installed by default in Adam 1.3's image.
All i did was replace the opks and enable again Simple Menu as default.

I have tried to play a couple of games and save something, created the favorite games' section and reboot a few times and so far so good.

**Comment by eduardofilo** [comment]
> Thanks again for taking your time on commenting on this. Just to be clear, I understand where the issue could be (i still didn't have the time to downgrade and confirm it 100%), in Simple Menu. And I am grateful for the options given here. On the other hand, if the issue is in Simple Menu but those issues were brought here, within Adam's build, there is in theory something that could be done. If a bad build caused a regression/issue in the software, there should be a rollback, in the way of maybe uploading a new Adam's build with a healthy version of Simple Menu. The reason I am saying this is because not everybody may realize there is a closed topic around this (this one) and find the "temporary fix" until a new Adam image is built... and built Adam's image for the problem.
> 
> It could be also that I may be one of the few folks still using an RG350 and maybe nobody else will notice ;)
> 
> Anyhow, I'll check other Simple Menu's versions right away.
> 
> Thanks again and also thank you for this wonderful image.

The problem is that the situation is complex. And there is no clear cause-effect relationship. For example, I have not experienced the problems you have mentioned, and without data it is very difficult for me to make a decision such as to downgrade. It would be possible that version 10.2 has other similar or even worse problems. I can't make a decision without data. If someone consistently demonstrates how to produce the problems you mention, the decisions will be much clearer.

**Comment by eduardofilo** [comment]
> > 1. If you would like to keep Adam Image 1.3, disable Simple Menu as the default launcher following Eduardo steps and avoid the actions I described in my first post (Particularly DO NOT modify the .ini file that contains the consoles' admissable file extensions for each system)
> 
> I got into the boot loop without modifying any .ini file, just by using the console. Then i don't think these steps are needed to cause the issue

It gives me the impression that it must be some of the files you have on the external card that are causing the problem. In the past SimpleMenu was very sensitive to directories with many files that are often used on systems like DOSBox or ScummVM. That situation improved, but I was left with the feeling that those systems were more complicated to manage.

As I mentioned before, without a clear cause-effect we cannot move forward. Try activating the SimpleMenu log (inside the config.ini file) to see if it gives us any clues. It would also be good, since your installation is prone to have problems, that you carry out a trial/error investigation by removing all the ROMs you have on the external and adding them little by little until the problem appears. I know it is a long job. If I had your external card I would do it myself.

**Comment by eduardofilo** [comment]
> It seems that with the 10.3 the device is working as expected. I am not very proficient with Simple Menu and all its versions yet, i used to have other OS with GMenu2x before. In order for it to make it work, i needed the SimpleMenu-OD-BETA.opk and not the -OD.opk Not sure what the differences are but the -OD.opk doesn't boot. The -OD-BETA one shares the name with the one that was installed by default in Adam 1.3's image. All i did was replace the opks and enable again Simple Menu as default.
> 
> I have tried to play a couple of games and save something, created the favorite games' section and reboot a few times and so far so good.

Yes, the correct version for Adam is OD-BETA: https://github.com/fgl82/simplemenu/releases/download/10.3/SimpleMenu-OD-BETA.opk

One of the reasons why I am reluctant to go back to version 10.2 or 10.3, is that the one that was installed in Adam 1.3 (it is a release candidate for SM v11) there is a major improvement. Settings made at the ROM level are stored in directories depending on the system. In 10.3 and before, they were all in the same directory and there were collisions that caused the application to close. That's what I meant by downgrading can be worse in general.

**Comment by borderomm** [comment]
@eduardofilo Thanks for your multiple detailed answers.
As i am using the console for my kids and it is working now, I'd rather leave it for now as it is, as it seems we were only two people having this issue and the OP has not come back in a while with these issues.

I guess the issue is related to everything what it was said before, maybe a file wrongly saved/corrupted.
Maybe it is not the consoles.ini but the favorites file (which i did use in the last attempt, as i always save a couple of games for my kids for easy access).

This 10.3 version works so far, the kids are now playing with it so, we can leave it as it is.

However, if you need a guinea pig, just let me know and you can reach out to me.

I'm expecting an RG280v so i may not use myself the RG350 anymore (it will be for the kids).

By the way, you can also reach out to me in Spanish if you prefer :)

**Comment by eduardofilo** [comment]
This image is complex. It is a mixture of software that is not "carrier grade" as it is said, that it is then used in different ways. Some parts will be more prone to failure and some users may luckily not touch the problem parts. Finding those problems and doing our part to help developers fix them is fun too. But it takes time and patience.

@borderomm Where are you from then?

**Comment by borderomm** [comment]
> @borderomm Where are you from then?

Spain, like you ;)

**Comment by fantinomaurizio** [comment]
> Closed? Is there a solution without the need to delete the sav file each time it happens? I needed to do this at least 3 times today.

I closed the thread since a solution was found like using GMenu2X as default launcher. If you believe it is worthy to reopen the thread till the finding of a complete solution.

**Comment by borderomm** [comment]
Hey @fantinomaurizio 
Actually, there was quite a long conversation during the past days so, I guess I'll let @eduardofilo take the shot here.

thanks for coming back to this issue though :)

**Comment by fantinomaurizio** [comment]
> Hey @fantinomaurizio Actually, there was quite a long conversation during the past days so, I guess I'll let @eduardofilo take the shot here.
> 
> thanks for coming back to this issue though :)

I went through the discussion and indeed I thought that it was more a workaround than a complete solution, but at the same time I guess that Eduardo will not be able to fix it easily since he has integrated and packed components for his image.

Let's wait for @eduardofilo to decide whether to close this issue or not.

**Comment by eduardofilo** [comment]
As you say, it is not in my hands to give the final solution to the problem, but does to investigate it and/or help the developer to find it. So I'll leave the issue open so I don't lose sight of it. Thanks for your comments, and any info will be welcome.

**Comment by fantinomaurizio** [comment]
Few comments after some days of testing. After having deleted the SimpleMenu opk reboot the RG350 and reinstalled the SimpleMenu opk I have not experienced the loop of death anymore, even with intesive change of files on the sdcard...

I have no idea if as @borderomm was mentioning is or was just a permission issue...

**Comment by AloBautist** [comment]
just confirming, same thing happen on RG280v (usually after overclocking FBA games), hope fix is released soon.

**Comment by DjFIL007** [comment]
New to this, but can also confirm my RG280V is having these instability issues on 1.3, but not on 1.2. Hopefully this is addressed eventually, but 1.2 seems fine to me for now.

**Comment by eduardofilo** [comment]
From your comments, for the moment the best workaround is to install the version of SimpleMenu that was in Adam 1.2. Currently the file has been removed from the release of the version that I installed. So I have pulled it from Adam 1.2 and attached it here.

I am going to prepare a version of Adam 1.3 with that version of SimpleMenu. But I already warn that you have the danger that ROM-level settings can cause conflicts between systems when the ROMs have the same name, which was one of the things that was improved in the version of SimpleMenu that I originally installed in Adam 1.3.

Despite the workaround, I insist that much of the software installed on Adam is not perfect. You have to learn to handle it in the sense of avoiding the problems that it can cause. For example, with SimpleMenu, whenever changes are to be made to the external card (adding or deleting ROMs) or in its configuration files, it is important to deactivate the program as the default launcher. Test while making changes by manually launching SimpleMenu from GMenu2X. If it refuses to start, try to delete the file `last_state.sav` and if it still doesn't work, double-check the changes made.

Thank you for your respectful comments and I apologize for not trying a solution earlier.

[SimpleMenu-OD-BETA.opk.zip](https://github.com/eduardofilo/RG350_adam_image/files/7574324/SimpleMenu-OD-BETA.opk.zip)

**Comment by eduardofilo** [comment]
Here you go: [https://github.com/eduardofilo/RG350_adam_image/releases/tag/v1.3.1](https://github.com/eduardofilo/RG350_adam_image/releases/tag/v1.3.1)

**Comment by DjFIL007** [comment]
Working great, no issues since installed 2 days ago. Thanks!

PS: a nice small idea for QOL for future update, please add more shortcuts (like brightness and sleep mode) to the help menu, since the second page is half empty as is. Cheers!

**Comment by eduardofilo** [comment]
> Working great, no issues since installed on my RG280V 2 days ago. Thanks!
> 
> PS: a nice small idea for QOL for future update, please add more shortcuts (like brightness, sleep mode and screenshot) to the help menu, since the second page is half empty as is. Cheers!

I don't develop SimpleMenu, only integrate it in the image. In any case, its developer had made several changes of that type in the release candidate version that was in Adam 1.3 and that will return to the image when FGL82 releases the final version.

**Comment by eduardofilo** [comment]
> @eduardofilo worked instantly thanks, I was previously in reboot loop after tried to use sound mixer. One small thing, on the instructions the unzip command says to use password od for the sudo password but in fact still untoqebboqvboqudrn for me

I was really wrong about that thing. This afternoon I have verified that it works to type anything password to execute sudo. I don't know if it's a bug in OD beta or a feature. I'm going to change the instructions, thanks.

**Comment by eduardofilo** [comment]
> Is there any point in getting v1.3.1 if v1.3 works fine?

Sorry, I'm not sure if you're asking if it's worth it to update or if you can upgrade to 1.3.1 from 1.3. For the first case, the improvement is SM stability and the possibility of exiting the loops in that launcher by pressing `B` at startup. For the second case, the option is to follow the instructions in the release.

https://github.com/eduardofilo/RG350_adam_image/releases/tag/v1.3.1

**Comment by eduardofilo** [comment]
I close this issue after the last satisfactory reports. Thanks...

**Comment by trislett** [comment]
This issue (boot looping) just happened to me on v1.3.1 after changing some of the playstation settings.

**Comment by eduardofilo** [comment]
> This issue (boot looping) just happened to me on v1.3.1 after changing some of the playstation settings.
> 
> Edit: Not the ideal solution, but I fixed it by deleting local/home/.simplemenu/last_state.sav as suggested on a previous post.

It is inevitable that it happens from time to time when the synchronization between that file and the structure of directories and files that SimpleMenu runs through is lost. For example, by deleting the last ROM of any list with the shortcut `B + X`, the startup loop happens systematically.

**Comment by mchenier** [comment]
You can also delete local/home/.simplemenu/last_state.sav by using DiskGenius free version.
It's was simpler for me.

**Comment by eduardofilo** [comment]
As commented in discussion #116 better disabling SimpleMenu as default frontend pressing B key during boot and then using Commander to delete the file. Other good alternative is to login through SSH/USB cable and deleting the file with `rm` command.
DiskGenius corrupts the ext4 partition easily.

**Comment by dhalper1** [comment]
I ran into this issue again in version 2.1 of adam image after using a lot of PS emulation beforehand.  Was unable to find the last_state.sav file.  But booted with pressing the B key and then opened simplemenu that way which worked.  Then I used the commander to delete the last_state.sav file, which appeared after that.
